// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// As variáveis de ambiente devem ser definidas no seu arquivo .env
// Ex: VITE_SUPABASE_URL="https://your-project-id.supabase.co"
// Ex: VITE_SUPABASE_ANON_KEY="your-anon-key"
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("As variáveis de ambiente VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY devem ser definidas.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);