// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://idjzzxirjcqkhmodweiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkanp6eGlyamNxa2htb2R3ZWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NTc3NzUsImV4cCI6MjA3NzEzMzc3NX0.SwRwtA8AC0rPDZTqWFikzCEamvdsqAYPiSuRYH0FJc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);